services:
  my-web-server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./server:/usr/share/nginx/html:ro
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    restart: always
